# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8f55c712e9da6c2ca7bb2c062d05a79bb82fd5a94a52c16d5e818798ffd109567bf2c813352cce576bb9e4a502c56d9b02cdcf8ac3ad6758961349d00574cd

test:
  secret_key_base: 6d8a2f9cee9d875292d3f140e93c70b063fc218fac77e8bd69e2be6c5d803855c4c7f63425447adbaf26d9a7c9cb31083c5b0eceaf5e96d494875219bb3ffec3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
